# Generated by Django 4.1.2 on 2022-10-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
